name: linting_check

on: [push]

jobs:
  yaml-linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: yaml linting
        # see https://yamllint.readthedocs.io/en/stable/configuration.html
        run: |
          success=0
          for i in `find . -name "*.yaml" -type f`; do
            echo "Processing $i"
            yamllint -d relaxed $i
            res=$?
            success=$((res+success))
          done
          exit $success
